//
// Created by cameron on 9/6/2019.
//

#ifndef CHIP8_CONSTANTS_H
#define CHIP8_CONSTANTS_H

#define FONTSET_SIZE 80u
#define FONTSET_START_ADDRESS 0x50u
#define FONT_CHARACTER_SIZE 0x5u

#define CHIP8_ROM_START 0x200u

#define VIDEO_WIDTH 64u
#define VIDEO_HEIGHT 32u

#define MEMORY_SIZE 4096u
#define REGISTER_COUNT 16u
#define STACK_SIZE 16u

#define SPRITE_WIDTH 8u

#define SCREEN_PIXEL_ON 0xFFFFFFFF
#define SCREEN_PIXEL_OFF 0x00000000

#endif //CHIP8_CONSTANTS_H
